# Generated by Django 3.2.19 on 2023-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='date_posted',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='date_posted',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
